apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.100.41 # Replace with the IP address of your NFS server
    path: /data/jenkins # Replace with the actual path on the NFS server
