apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secrets
  namespace: mariadb
type: Opaque
data:
  root-password: cjROQCE1SmM4TXFuYyQkMVJTaUtNWER1
  db-username: cm5jbHVzZXI=
  db-password: bSVVNzB6Wlp3bTRibHlHbTEqKm8zNEom

